[project]
name = "insurance-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docxtpl>=0.20.2",
    "faker>=40.1.0",
    "flask>=3.1.2",
]
